nacos-addr: 182.160.5.25:8848
#nacos-addr: 127.0.0.1:8848
namespace-dev: dc3b7bba-da77-4789-b816-fdf69813515b
namespace-test: ac896072-395d-416a-8b63-b491e8893ed7
# 应用名称
server:
  servlet:
    context-path: /system
  port: 8090
spring:
  application:
    name: xuecheng-system
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      server-addr: ${nacos-addr}
      username: nacos
      password: nacos
      config:
        namespace: ${namespace-${spring.profiles.active}}
        group: ${spring.application.name}
      discovery:
        namespace: ${namespace-${spring.profiles.active}}
    config:
      override-none: true
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.yml
      - optional:nacos:swagger-xuecheng.yml?refreshEnabled=true&group=xuecheng
      - optional:nacos:mybatis-xuecheng.yml?refreshEnabled=true&group=xuecheng
      - optional:nacos:redis-xuecheng.yml?refreshEnabled=true&group=xuecheng
  redis:
    host: 182.160.5.25
    port: 6379
    password: redis
    database: 1
  datasource:
    url: jdbc:mysql://182.160.5.25:3306/xc_system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
